version: '3.9'

services:
  plazoleta_container:
    container_name: plazoleta_container
    image: josuebladek/small-square-microservice-v2:latest
    build: .
    ports:
      - 8091:8091
    environment:
      - DATABASE_URL=jdbc:postgresql://database-1.cm2dbp6lmztp.us-east-1.rds.amazonaws.com:5432/small-square
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - FEIGN_USER_URL=192.168.0.6:8090