server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://database-1.cm2dbp6lmztp.us-east-1.rds.amazonaws.com:5432/small-square
    username: postgres
    password: postgres
#    url: ${BD_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
    platform: postgres
    driverClassName: org.postgresql.Driver
  application:
    name: smallsquare-microservice

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

application:
  security:
    jwt:
      secret-key: SDF89SD9F876556A586E3SDFSD9F87SDFB62SDF987SDF897SD
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

feign:
  user:
    url: 192.168.0.6:8090

twilio:
  account-sid: AC3047a197f006fc8c80c61b4fb6493ed3
  auth-token: 5837bb5a9a6c04d74df2dd639719c8a3
  phone-number: +14178043060