server:
  port: 8091

spring:
  application:
    name: smallsquare-microservice
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/small-square
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: SDF89SD9F876556A586E3SDFSD9F87SDFB62SDF987SDF897SD
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days