server:
  port: 8091

spring:
  application:
    name: smallsquare-microservice
  datasource:
    #    url: jdbc:postgresql://localhost:5432/small-square
    #    username: postgres
    #    password: 1234
    #    url: jdbc:postgresql://database-1.cm2dbp6lmztp.us-east-1.rds.amazonaws.com:5432/small-square
    #    username: postgres
    #    password: postgres
    #    driverClassName: org.postgresql.Driver
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://database-1.cm2dbp6lmztp.us-east-1.rds.amazonaws.com:5432/small-square
    username: postgres
    password: postgres
    platform: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

application:
  security:
    jwt:
      secret-key: SDF89SD9F876556A586E3SDFSD9F87SDFB62SDF987SDF897SD
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

feign:
  user:
#    url: ${FEIGN_USER_URL}
    url: 192.168.0.6:8090

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}