name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      # Step 3:
      - name: Build and run tests with Gradle
        run: ./gradlew build --stacktrace --info

      # Step 4:
      - name: Run SonarQube analysis
        run: ./gradlew sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker image
        run: |
          docker build --tag small-square-microservice-v3 .
          docker tag small-square-microservice-v3 561506039848.dkr.ecr.us-east-1.amazonaws.com/docker-image-repository

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 561506039848.dkr.ecr.us-east-1.amazonaws.com/docker-image-repository

      - name: Notify fails in Google chat
        if: ${{ failure() }}
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{
            "text": "Se produjo un fallo en el flujo de trabajo de GitHub Actions. Revisa el registro para obtener más detalles: ${{ github.event.workflow_run.url }}"
          }' $GOOGLE_CHAT_WEBHOOK_URL
      ##################################################################################################################

#      # Step 5:
#      - name: Build Docker image
#        run: docker build -t small-square-microservice-v3 .
#
#      # Step 6:
#      - name: Tag Docker image
#        run: docker tag small-square-microservice-v3 ${{ secrets.DOCKERHUB_USERNAME }}/small-square-microservice-v3:latest
#
#      # Step 7:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # Step 8:
#      - name: Push Docker image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/small-square-microservice-v3:latest
