name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build and run tests
        run: ./gradlew clean build

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          organization: "josuepragma"
#          token: ${{ secrets.SONAR_TOKEN }}
#          distribution: "sonarcloud"