name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      # Step 3:
      - name: Build and run tests with Gradle
        run: ./gradlew build --stacktrace --info

      # Step 4:
#      - name: Run SonarQube analysis
#        run: ./gradlew sonarqube
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      #################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.IAM_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.IAM_SECRET_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: AKIAYFPC6HAUNWCBSQAO
#          aws-secret-access-key: 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
#          aws-region: us-west-2
#
#      - name: Log in to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v1
#        with:
#          registry: 561506039848.dkr.ecr.us-west-2.amazonaws.com
#
#      - name: Build and tag Docker image
#        run: docker buildx build --file Dockerfile --tag small-square-microservice-v3 .
#
#      - name: Push Docker image to ECR
#        run: |
#          docker tag small-square-microservice-v3 561506039848.dkr.ecr.us-west-2.amazonaws.com/small-square-microservice-v3:latest
#          docker push 561506039848.dkr.ecr.us-west-2.amazonaws.com/small-square-microservice-v3:latest

#      - name: Build and Tag Docker image
#        run: |
#          docker build --tag small-square-microservice-v3 .
#          docker tag small-square-microservice-v3 561506039848.dkr.ecr.us-east-1.amazonaws.com/docker-image-repository
#
#      - name: Push Docker image to Amazon ECR
#        run: |
#          docker push 561506039848.dkr.ecr.us-east-1.amazonaws.com/docker-image-repository

      #################
      # Step 5:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()


#      # Step 6:
#      - name: Build Docker image
#        run: docker build -t small-square-microservice-v3 .
#
#      # Step 7:
#      - name: Tag Docker image
#        run: docker tag small-square-microservice-v3 ${{ secrets.DOCKERHUB_USERNAME }}/small-square-microservice-v3:latest
#
#      # Step 8:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          registry: docker.io
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # Step 9:
#      - name: Push Docker image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/small-square-microservice-v3:latest
