name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

#      - name: Cache SonarCloud dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar

#      - name: Build and run tests
#        run: ./gradlew clean build

      - name: SonarQube analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}